import React from "react";
import { motion } from "framer-motion";
import { CheckCircle2, Circle, BrainCircuit, Target, Shield, Zap, Search, Activity } from "lucide-react";
import { Badge } from "@/components/ui/badge";

interface InvestigationRoadmapProps {
  content: string;
  onToggleTask?: (taskId: string) => void;
}

export function InvestigationRoadmap({ content, onToggleTask }: InvestigationRoadmapProps) {
  // Parse markdown tasks from the content
  const rawPhases = content.split(/### Phase \d+: /).filter(Boolean);
  const phaseNames = ["Immediate Leads", "Digital Trail Analysis", "Communication Networks", "Field Operations"];

  // Calculate overall progress
  const allTasks = content.match(/- \[[ x]\]/g) || [];
  const completedTasks = content.match(/- \[x\]/g) || [];
  const progressPercent = allTasks.length > 0 ? Math.round((completedTasks.length / allTasks.length) * 100) : 0;

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-8 gap-4">
        <div>
          <h2 className="text-xl font-black font-mono tracking-tighter text-primary flex items-center gap-2">
            <BrainCircuit className="h-6 w-6" />
            INTELLIGENCE STRATEGY
          </h2>
          <p className="text-[10px] text-muted-foreground uppercase tracking-widest mt-1">Operational Directives Generated by Chanakya AI</p>
        </div>
        <div className="flex flex-col items-end gap-1">
          <div className="flex items-center gap-3 mb-1">
            <span className="text-[10px] font-mono text-primary/60 uppercase font-bold tracking-widest">{progressPercent}% OPERATIONAL READY</span>
            <Badge variant="outline" className="bg-primary/5 text-primary border-primary/20 font-mono text-[9px] px-2">
              MISSION STATUS: ACTIVE
            </Badge>
          </div>
          <div className="h-1.5 w-48 bg-secondary rounded-full overflow-hidden mt-1 hidden sm:block border border-white/5">
            <motion.div 
              initial={{ width: 0 }}
              animate={{ width: `${progressPercent}%` }}
              transition={{ duration: 1, ease: "circOut" }}
              className="h-full bg-primary shadow-[0_0_10px_rgba(var(--primary-rgb),0.5)]"
            />
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {rawPhases.map((phaseContent, idx) => {
          const lines = phaseContent.split("\n");
          const tasks = lines.filter(t => t.trim().startsWith("- ["));
          const phaseName = phaseNames[idx] || `Phase ${idx + 1}`;
          
          return (
            <motion.div 
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 }}
              className="group relative"
            >
              <div className="absolute -inset-0.5 bg-gradient-to-br from-primary/20 to-transparent rounded-2xl blur opacity-0 group-hover:opacity-100 transition duration-500" />
              <div className="relative bg-black/40 backdrop-blur-md border border-primary/10 rounded-2xl p-5 hover:border-primary/30 transition-all h-full flex flex-col">
                <div className="flex items-center gap-3 mb-4">
                  <div className="h-9 w-9 rounded-xl bg-primary/10 flex items-center justify-center border border-primary/20 shadow-[0_0_15px_rgba(var(--primary-rgb),0.1)]">
                    {idx === 0 && <Target className="h-4 w-4 text-primary" />}
                    {idx === 1 && <Zap className="h-4 w-4 text-primary" />}
                    {idx === 2 && <Activity className="h-4 w-4 text-primary" />}
                    {idx === 3 && <Shield className="h-4 w-4 text-primary" />}
                  </div>
                  <div>
                    <h3 className="text-[10px] font-black font-mono tracking-[0.2em] text-primary/60 uppercase">PHASE 0{idx + 1}</h3>
                    <h4 className="text-sm font-bold text-foreground tracking-tight">{phaseName}</h4>
                  </div>
                </div>

                <div className="space-y-3 flex-1">
                  {tasks.length > 0 ? tasks.map((task, tIdx) => {
                    const isCompleted = task.includes("[x]");
                    const cleanTask = task.replace(/- \[[ x]\]/, "").trim();
                    
                    return (
                      <div 
                        key={tIdx} 
                        className={`group/item flex gap-3 p-3 rounded-xl transition-all cursor-pointer border ${
                          isCompleted 
                            ? 'bg-primary/5 border-primary/5 opacity-50' 
                            : 'bg-secondary/10 border-white/5 hover:bg-secondary/30 hover:border-primary/20 shadow-sm'
                        }`}
                        onClick={() => onToggleTask?.(`${idx}-${tIdx}`)}
                      >
                        <div className="shrink-0 mt-0.5">
                          {isCompleted ? (
                            <CheckCircle2 className="h-4 w-4 text-primary" />
                          ) : (
                            <Circle className="h-4 w-4 text-muted-foreground/30 group-hover/item:text-primary/50 transition-colors" />
                          )}
                        </div>
                        <div className="flex flex-col gap-1.5 flex-1">
                          <p className={`text-xs leading-relaxed ${isCompleted ? 'line-through text-muted-foreground' : 'text-foreground/90'}`}>
                            {cleanTask}
                          </p>
                          {!isCompleted && (
                            <div className="flex items-center gap-2">
                              <span className="text-[8px] font-mono uppercase px-1.5 py-0.5 rounded bg-primary/10 text-primary border border-primary/10">Priority Analysis</span>
                              <span className="h-1 w-1 rounded-full bg-muted-foreground/30" />
                              <span className="text-[9px] text-muted-foreground/60 font-medium">Pending Data Validation</span>
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  }) : (
                    <p className="text-[10px] text-muted-foreground italic px-2 py-4">No directives identified for this phase.</p>
                  )}
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
